---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-server
  name: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-server
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
      - image: postgres:15
        name: postgres-server
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-server-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-server-secrets
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-server-secrets
              key: POSTGRES_DB
        

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-server
spec:
  selector:
    app: postgres-server
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP 
